language: node_js

node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: 8d1af185-3941-4d01-8fec-79a3622d7c0a
  app: video-cloud
  on:
    all_branches: true
